name: perfect-pour
version: "v0.19.0-b1"
summary: Perfect Pour
description: |
  Pour Drinks! It's fun!
base: core20
grade: stable
confinement: strict
compression: lzo # might decrease install/upgrade time
architectures:
  - build-on: amd64
plugs:
  wine-runtime-c20:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime-core20
  wine-7-devel:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-7-devel-core20

environment:
  WINEDLLOVERRIDES: "mscoree,mshtml="  # Prevent pop-ups about Wine Mono and Wine Gecko
  RUN_EXE: "$SNAP/PerfectPour_v0-19-0b1_Windows64_Standalone_Cheats/perfect-pour.exe"
  SOMMELIER_KEEP_CWD: "1"  # Don't change the working directory so relative paths still work
  NO_AT_BRIDGE: "1"  # Fix yad error Failed to connect to socket /tmp/dbus-xxx: No such file or directory
  DISABLE_WAYLAND: "1"  # Fix gtk decoration under wayland session
  SYSTEM_WGETRC: $SNAP/wine-runtime/etc/wgetrc

parts:
  perfect-pour:
    plugin: dump
    source: PerfectPour_v0-19-0b1_Windows64_Standalone_Cheats.zip
    override-build: |
      snapcraftctl build
      cd $SNAPCRAFT_PART_INSTALL/PerfectPour_v0-19-0b1_Windows64_Standalone_Cheats
      mv Perfect\ Pour.exe perfect-pour.exe
      mv Perfect\ Pour_Data/ perfect-pour_Data
      snapcraftctl set-version "v0.19.0-b1"
    build-packages: 
      - wget
  sommelier:
    plugin: make
    source: https://github.com/snapcrafters/sommelier-core.git
    source-branch: "master"
    build-packages:
      - libc6-dev-i386
      - gcc-multilib

  # This reverts changes from https://github.com/snapcore/snapcraft/pull/3586
  fix-fontconfig:
    plugin: nil
    after: [gnome-3-38-extension]
    override-prime: |
      sed -i '/snap-package/,+1d' $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch

  fix-bindtext:
    plugin: nil
    after: [gnome-3-38-extension]
    override-prime: |
      sed -i "$(grep -in bindtext $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch | cut -d':' -f1 | tail -2 | head -1)d" $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch
      sed -i "$(grep -in bindtext $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch | cut -d':' -f1 | tail -1)d" $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch
apps:
  perfect-pour:
    extensions: [ gnome-3-38 ]
    command: bin/sommelier run-exe
    plugs:
      - audio-playback
      - opengl
      - home
      - network
      - hardware-observe
      - process-control
      - cups-control
      - removable-media
  wine:
    extensions: [ gnome-3-38 ]
    command: bin/sommelier
    plugs:
      - home
      - network
      - hardware-observe
      - process-control
      - cups-control
      - removable-media
  # The winetricks command can be used to run winetricks inside the wine
  # environment that this snap uses.
  winetricks:
    extensions: [ gnome-3-38 ]
    command: bin/sommelier winetricks
    plugs:
      - network
