name: nidhogg-2
version: "2023071301"
summary: Nidhogg 2 build from Game Maker Studio version 2
description: |
  Outsmart your opponents with all kinds of weapons in this life or death tug-of-war that ends in the belly of a flying worm.
  The next installment of the epic award-winning dueling tug-of-war is coming! Stab, shoot, slice, or stomp your opponent to gain control of the screen, then book it to your side of the arena. Before long, a new opponent will appear in your way. If they kill you, they get control. Get all the way to your end of the arena to win–and be devoured by the Nidhogg. Enjoy new monstrous visuals by artist Toby Dixon and bangin beats from Mux Mool, Daedelus, Doseone, and more!
base: core18
grade: stable 
confinement: strict
compression: lzo # might decrease install/upgrade time
parts:
  nidhogg-2:
    stage-packages:
      - libasn1-8-heimdal
      - libasound2
      - libasound2-data
      - libasound2-plugins
      - libcurl3-gnutls
      - libgl1
      - libglu1-mesa
      - libglvnd0
      - libglx0
      - libgssapi3-heimdal
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libkrb5-26-heimdal
      - libldap-2.4-2
      - libnghttp2-14
      - libopenal1
      - libpsl5
      - libroken18-heimdal
      - librtmp1
      - libsasl2-2
      - libsndio6.1
      - libwind0-heimdal
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxrandr2
      - libxrender1
      - libxxf86vm1
    plugin: dump
    source: Nidhogg-2_GMS2_2023071301.zip
    after:
      - desktop-glib-only
  desktop-glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin
apps:
  nidhogg-2:
    command: bin/desktop-launch $SNAP/Nidhogg_2_GMS2
    plugs:
      - opengl
      - x11
      - audio-playback
      - desktop
      - desktop-legacy
      - screen-inhibit-control
      - joystick
